version: "3.2"
services:
  wp:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./twentyseventeen:/var/www/html/wp-content/themes/twentyseventeen
    environment:
     - WORDPRESS_SITE_URL=localhost
     - WORDPRESS_HOME_URL=localhost
     - WORDPRESS_DB_USER=wordpress
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_HOST=db  
    depends_on:
      - db    
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
       MYSQL_USER: wordpress
       MYSQL_ROOT_PASSWORD: root
       MYSQL_PASSWORD: password
       MYSQL_DATABASE: wordpress