apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress-db
    spec:
      containers:
      - image: mysql:5.7
        name: wordpress-db
        env:
        - name:  MYSQL_USER
          value: wordpress
        - name:  MYSQL_ROOT_PASSWORD
          value: root
        - name:  MYSQL_PASSWORD
          value:  password
        - name:  MYSQL_DATABASE
          value:  wordpress
        ports:
          - containerPort:  3306
            name:  wordpress-db
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: wordpress-data
      volumes:
        - name: wordpress-data
          hostPath:
            path: /root/mysql
            type: Directory