apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  wp
  labels:
    name:  wp
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  wp
    spec:
      containers:
      - image: quay.io/zakariaamine/wp-nginx-demo  
        name:  wp
        resources:
          requests:
            cpu: "20m"
            memory: "1Gi"
        env:
        - name:  WORDPRESS_SITE_URL
          value: 167.99.88.86
        - name:  WORDPRESS_HOME_URL
          value: 167.99.88.86
        - name:  WORDPRESS_DB_USER
          value:  wordpress
        - name:  WORDPRESS_DB_PASSWORD
          value:  password
        - name:  WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: hostname-config
              key: db_host                       
        ports:
        - containerPort:  80
        volumeMounts:
          - mountPath: /var/www/html/wp-content/themes/twentyseventeen
            name: wordpress-theme
      volumes:
        - name: wordpress-theme
          hostPath:
            path: /home/wordpress-docker-kubernetes/twentyseventeen
            type: Directory